### ISSUE TITLE
How to do async request?

### ISSUE THREAD

**Issue by prashant-pokhriyal** [rjvandoesburg/laravel-jira-rest-client#14]
I have an array of Jira issues id and I want to iterate over each id and get the details of all the issues. I do not want to do it synchronously. How can I achieve this?

**Comment by rjvandoesburg** [comment]
This can be achieved either using JS (if you want to call it from the front-end) or by using queues (non-sync) 
See Laravel docs for more information: https://laravel.com/docs/5.8/queues

**Comment by prashant-pokhriyal** [comment]
I cannot make use of laravel queues, as once I get all the issue details, I'm sending it to the client. So my approach is as follows:
* Make async requests to jira api
* Wait for all the responses
* Once all responses received, send it to the client.

I see you are making use of `guzzlehttp` library. This library gives support to make [asnyc requests](http://docs.guzzlephp.org/en/stable/faq.html#can-guzzle-send-asynchronous-requests). If possible can you enable that functionality in your library?

**Comment by rjvandoesburg** [comment]
I've pushed a change to the master (not tested, but in theory it should work)
Now you should be able to create a request, enable async, and perform the request
```php
$request = app(UserRequest::class);
$request->async()->search();
```
This will return a `\GuzzleHttp\Promise\PromiseInterface`
Could you let me know if this works for you?

**Comment by prashant-pokhriyal** [comment]
Can I download the latest changes using composer?

**Comment by rjvandoesburg** [comment]
Yes but because it is not pushed to a tag you have to require the master branch
`composer require rjvandoesburg/laravel-jira-rest-client "dev-master"`

**Comment by prashant-pokhriyal** [comment]
Thank you it's working now.

**Comment by prashant-pokhriyal** [comment]
May I know, when are you planning to make a tag? I cannot use dev branch

**Comment by rjvandoesburg** [comment]
I pushed to tag `3.0.0-beta8` hope that's enough for you :)
