### ISSUE TITLE
Override the oAuth middleware

### ISSUE THREAD

**Issue by Chernitsov** [rjvandoesburg/laravel-jira-rest-client#15]
Hi there,

In my application i use oAuth to authenticate the users. In my own OAuthController where i do the oAuth dance, i store the received tokens in the Database in relation to the user. My problem is now:

I want to use the stored tokens for the requests. Where i can clearly override or add a own OAuth Middleware where i get the tokens from the database instead of the session?

Or is my way not good and anyone have a better solution for this case?

**Comment by Chernitsov** [comment]
ok, I should maybe first look in the configuration file ..

**Comment by rjvandoesburg** [comment]
I wasn't able to respond to you past weekend but I'm glad you worked it out!
