### ISSUE TITLE
composer require error

### ISSUE THREAD

**Issue by fullmvc** [rjvandoesburg/laravel-jira-rest-client#16]
Hello,

I need to use a jira client and i wnat t use this package, but i can't download it via `composer require https://github.com/rjvandoesburg/laravel-jira-rest-client.git`.
It says:
` Could not parse version constraint //github.com/rjvandoesburg/laravel-jira-rest-client.git: Invalid version string
  "//github.com/rjvandoesburg/laravel-jira-rest-client.git"`

And composer also reported a `description : The property description is required` error, when I run `composer validate` on the composer json.

**Comment by rjvandoesburg** [comment]
Could you try `composer require rjvandoesburg/laravel-jira-rest-client` instead?

**Comment by fullmvc** [comment]
Thank you, that's solved the problem!
Keep up the good work!
