### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by clizaola** [rjvandoesburg/laravel-jira-rest-client#2]
Replace the lines 
$issue = jira()->issues()->get('ISSUE-3'); 
and 
$issue = \Jira::issues()->get('ISSUE-3');

For the correct implementation
$issue = jira()->issue('ISSUE-3')->get(); 
and 
$issue = \Jira::issue('ISSUE-3')->get();

**Comment by clizaola** [comment]
I have the PR here #3

**Comment by rjvandoesburg** [comment]
Cheers for the PR!
