### ISSUE TITLE
Clone Jira project settings, boards, issues, ...?

### ISSUE THREAD

**Issue by Sebi94nbg** [rjvandoesburg/laravel-jira-rest-client#20]
I have a Jira project with some default settings, sample tickets, a configured board and some already defined issues types as well as workflows.

I would like to create a new Jira project using this Rest API and clone everything from the Jira project template.

To be more specific: The following things needs to be cloned / copied:

- Project settings
  - Issue types
  - Issue layout
  - Workflows
  - Fields
  - Components
  - People & Permissions
- Issues
  - There are some sample issues, which I would like to clone / copy based on the requirements (so I only want to clone / copy those, which I need)
- Kanban board
  - Incl. all board settings from the template project

Is this possible and if yes: How?

Related issue: #13

**Comment by rjvandoesburg** [comment]
Well I don't know about cloning (can't find any reference in the docs: https://developer.atlassian.com/cloud/jira/platform/rest/v3/) 

But you can create a new project and set a lot of the values after creating a project.

Have a look in https://github.com/rjvandoesburg/laravel-jira-rest-client/tree/master/src/Requests/Project for the methods that are currently implemented (as not all methods are implemented yet).

As for issues, you can fetch the issues you want to 'clone' read them out and then create a new request where you can create a new issue. Have a look at the Atlassian documentation on how to pass the fields: https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-issue-post

Using the package you can do `app(IssueRequest::class)->create($parameters)` for instance.

As for boards, doesn't seem to be a copy one either so again, fetch the data an create a new one: https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Board

**Comment by Sebi94nbg** [comment]
Mm, too bad. But thank you very much for the workaround!

Hopefully this will be supported in future by Atlassian and this Rest API.
