### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by maartenhetworks** [rjvandoesburg/laravel-jira-rest-client#21]
How can I create a project? 

Call: (/rest/project-templates/1.0/createshared/)

**Comment by rjvandoesburg** [comment]
I can't find that endpoint in the documentation, all I could find is `POST /rest/api/3/project` https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-project-post
There you can provide the template you want to base your new project on.

Within the code you can do 
```php
$projectRequest = app(ProjectRequest::class);

$projectRequest->create($parameters);
```
and pass all the parameters you require. See the Atlassian docs for available parameters.

**Comment by galazzaroni** [comment]
Does it work for Laravel 7?

**Comment by rjvandoesburg** [comment]
@galazzaroni Using the tag `3.0.0-beta10` will allow you to use the package with L7, however I have not tested it as I don't have access to a Jira installation.
But looking at what changed over the last year I don't see much reason why it shouldn't work (except for changes on Atlassian's side)

**Comment by galazzaroni** [comment]
It works ok using Laravel 7. Thank you.
I have a question, I can't get all field custom, I need to get all field custom for then I do an global update.
Can you help me ?
Thank you
