### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by analytical42** [rjvandoesburg/laravel-jira-rest-client#24]
Hey! I'm getting this error when installing with composer require on Laravel 8.2:

**Your requirements could not be resolved to an installable set of packages.**

**Problem 1**
    - Installation request for rjvandoesburg/laravel-jira-rest-client ^1.0 -> satisfiable by rjvandoesburg/laravel-jira-rest-client[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

**Comment by rjvandoesburg** [comment]
Hey,

Thank you for reporting this issue, at the moment I am not in a position to update the package.
I was having the same issue using other packages and looks like this would not be a simple dependency bump.
If it is you could try that and create a pull request.

**Comment by analytical42** [comment]
See #25. By editing composer.json to also accept guzzle ^7, it worked for me on Laravel 8.

**Comment by DarkPrinceWW** [comment]
Same problem

**Comment by rjvandoesburg** [comment]
Heya, I've updated the dependency and the package will install again on L8. I however do not have access to a Jira instance to validate if the latest version of Guzzlehttp throws any errors.
