### ISSUE TITLE
Wrong namespace for class WorkflowRequest

### ISSUE THREAD

**Issue by RRR777** [rjvandoesburg/laravel-jira-rest-client#32]
When installing your package with composer, got notification:

Class Atlassian\JiraRest\Requests\User\WorkflowRequest located in ./vendor/rjvandoesburg/laravel-jira-rest-client/src/Requests/Workflow/WorkflowRequest.php does not comply with psr-4 autoloading standard. Skipping.

The correct namespace could be:
namespace Atlassian\JiraRest\Requests\Workflow;

**Comment by rjvandoesburg** [comment]
I have pushed a new tag `3.2.1` that fixes the namespace 👍
