### ISSUE TITLE
How to configure oauth authentication configuration?

### ISSUE THREAD

**Issue by JeffreyBool** [rjvandoesburg/laravel-jira-rest-client#4]
```php
<?php
'oauth' => [
            'consumer_key' => env('JIRA_CONSUMER_KEY', ''),
            'consumer_secret' => env('JIRA_CONSUMER_SECRET', ''),
            'private_key' => env('JIRA_PRIVATE_KEY', ''),
            'private_key_passphrase' => env('JIRA_PRIVATE_KEY_PASSPHRASE', '')
  ]
```

**Comment by rjvandoesburg** [comment]
OAuth is not yet implemented: https://github.com/rjvandoesburg/laravel-jira-rest-client#todo
I tried working on it before but had various issues and frankly I gave up for now.

Mostly because I had to work with a cookie jar for keeping the cookies and they didn't persist properly

**Comment by kenuocn** [comment]
你使用 cookie 的方式会出现401的问题吗? cookie 适用于静默授权码?

**Comment by rjvandoesburg** [comment]
Closing due to no new information.
