### ISSUE TITLE
Basic authentication problem

### ISSUE THREAD

**Issue by JeffreyBool** [rjvandoesburg/laravel-jira-rest-client#5]
When I get the problem successfully with the correct password, then I change the password to be wrong, the request will raise the 401 error again, and then change the password again will increase 401, this is the cookie caused?

**Comment by kenuocn** [comment]
就是我使用正确的账号密码使用 basic 认证方式, 可以成功获取 issue 问题,但是这时候我突然把密码改了,这时候就会出现401了, 再次改回正确的密码也不好使了.没有这个处理机制吗? 而且这个包好像没文档,我都是读你源码看的, 如果使用basic 密码错误过多,是不是 jira 就会拒绝了.

**Comment by rjvandoesburg** [comment]
Closing due to no new information.
