### ISSUE TITLE
oAuth

### ISSUE THREAD

**Issue by Chernitsov** [rjvandoesburg/laravel-jira-rest-client#8]
Hi, can you possibly explain how it works exactly with the oAuth?

**Comment by rjvandoesburg** [comment]
Hello Chernitsov 

First I would advise you to read the following: https://developer.atlassian.com/server/jira/platform/oauth/

After reading that you need to create an application on Jira's side (as explained on that page)

Once you've done all that you can install the package and head into the `.env` file and add the following:
```
JIRA_HOST={url of your Jira instance}
JIRA_CONSUMER_KEY={as set in Jira}
JIRA_PRIVATE_KEY={full path location to your key used for authentication}
```
These credentials should be enough to talk to the api to login, in `src/Http/Controllers/OAuthController.php` you can find how you can do the 'oauth' dance.
This controller can be enabled by setting `JIRA_OAUTH_ROUTES=true` in the `.env` file. This allows you to navigate to `/atlassian/jira/oauth/access` which will redirect you to Jira to grant access.

Once that is done you will find oauth tokens in the session which will allow you to request resources from Jira.

Alternatively you can set those credentials in the `.env` so you don't have to authenticate again 
```
JIRA_OAUTH_TOKEN=
JIRA_OAUTH_TOKEN_SECRET=
```

I hope this helps you!

**Comment by Chernitsov** [comment]
Thank you for the answer, unfortunately, comes with the error message:

> Class App\Http\Controllers\OAuthController does not exist

when I try to access the route `/atlassian/jira/oauth/access`. 

So the problem is that I can not call the controller from the vendor. Does the .env need to be configured before installation?

**Comment by rjvandoesburg** [comment]
Hmm, that is odd. Do the routes come up when you run `php artisan route:list --name=atlassian`?
![Screenshot 2019-03-11 at 10 04 05](https://user-images.githubusercontent.com/1488300/54111818-12977b80-43e5-11e9-8077-8f4eeb23de31.png)

If not than in the mean time I would ask you to copy the controller to your app and the routes as well and I will try to find out why this is not working for you.

What branch/version are you on? And while we're at it, what platform are you using?

**Comment by Chernitsov** [comment]
Oh sorry, that was my fault. I have redefined these routes in my `routes/web.php` myself. I have removed these again and now it works!

The authentication process is already running, but unfortunately the tokens are not stored in the session. Is this feature not provided or did I do something wrong?

**Comment by rjvandoesburg** [comment]
Ah sorry, the data is flashed https://laravel.com/docs/5.8/redirects#redirecting-with-flashed-session-data

This allows you to decide where to store the keys e.g. database or session.
Alternatively you can catch the event `Atlassian\JiraRest\Events\OAuth\AccessTokensReceived` to handle the tokens.

If you want to use session you need to store them as such:
```php
session()->put('atlassian.jira.oauth.tokens' => [
    'oauth_token' => $token,
    'oauth_token_secret' => $secret,
]);
```
Otherwise you need to set the values in the config, either in your `.env` or by setting the config via your code.

Hope this helps!

**Comment by rjvandoesburg** [comment]
Hello Chernitsov,

Have you solved this problem? If so, we can close this issue for future reference (but of course the docs will be updated as well)

Cheers

**Comment by Chernitsov** [comment]
Hello @rjvandoesburg,

I solved the problem by storing the passed parameters on the redirect route in the session with the following code

```php
Route::get('/', function () {

    $tokens = session('atlassian.jira.oauth.access_tokens');

    session()->put('atlassian.jira.oauth.tokens', [
        'oauth_token' => $tokens['oauth_token'],
        'oauth_token_secret' => $tokens['oauth_token_secret']
    ]);

    return view('welcome');
});
```

What bothers me at the moment is that the redirect url is automatically the previous page. But otherwise it serves its purpose! Thank you very much!

**Comment by rjvandoesburg** [comment]
Well, you could always copy the contents of the `Atlassian\JiraRest\Http\Controllers\OAuthController` to your app folder and trim what you don't need, that would allow you to store the tokens in the session right there.

So `JIRA_OAUTH_ROUTES` would have to be set to `false` in your `.env` and register the routes yourself.

**Comment by rjvandoesburg** [comment]
Updated the docs to explain how to use OAuth. Closing this issue.
